def Questions(): 
    return{
        1: {"question": "Who won the FIFA World Cup in 2018?", "answer": "France"},
        2: {"question": "What is the chemical symbol for water?", "answer": "H2O"},
        3: {"question": "Who discovered gravity?", "answer": "Isaac Newton"},
        4: {"question": "What sport is known as the 'king of sports'?", "answer": "Soccer"},
        5: {"question": "Who is the main character of the anime 'Naruto'?", "answer": "Naruto Uzumaki"},
        6: {"question": "What is the chemical name for table salt?", "answer": "Sodium Chloride"},
        7: {"question": "Which country hosted the 2020 Summer Olympics?", "answer": "Japan"},
        8: {"question": "Who invented the theory of relativity?", "answer": "Albert Einstein"},
        9: {"question": "In which game do players collect resources and build bases, called 'Minecraft'?", "answer": "Minecraft"},
        10: {"question": "What is the SI unit of force?", "answer": "Newton"},
        11: {"question": "Which sport uses a shuttlecock?", "answer": "Badminton"},
        12: {"question": "Who is the author of 'Death Note' anime?", "answer": "Tsugumi Ohba"},
        13: {"question": "What is the chemical formula of carbon dioxide?", "answer": "CO2"},
        14: {"question": "Who is known as the father of modern physics?", "answer": "Galileo Galilei"},
        15: {"question": "Which game is played on a 64-square board with black and white pieces?", "answer": "Chess"},
        16: {"question": "What is the speed of light in vacuum (approx.)?", "answer": "300,000 kilometers per second"},
        17: {"question": "Who is the famous anime character with spiky blonde hair and a headband?", "answer": "Naruto Uzumaki"},
        18: {"question": "What chemical element has the symbol 'O'?", "answer": "Oxygen"},
        19: {"question": "Which country invented table tennis?", "answer": "England"},
        20: {"question": "Who won the NBA championship in 2020?", "answer": "Los Angeles Lakers"},
        21: {"question": "What is the chemical symbol for gold?", "answer": "Au"},
        22: {"question": "Which sport uses a racket and a yellow ball, played on grass?", "answer": "Tennis"},
        23: {"question": "Who is the protagonist of the anime 'One Piece'?", "answer": "Monkey D. Luffy"},
        24: {"question": "What is the chemical formula of ammonia?", "answer": "NH3"},
        25: {"question": "Who discovered penicillin?", "answer": "Alexander Fleming"},
        26: {"question": "Which game involves building towers and defending against waves of enemies?", "answer": "Tower Defense"},
        27: {"question": "What is the SI unit of electric current?", "answer": "Ampere"},
        28: {"question": "Which sport uses a puck and is played on ice?", "answer": "Ice Hockey"},
        29: {"question": "Who wrote the anime 'Fullmetal Alchemist'?", "answer": "Hiromu Arakawa"},
        30: {"question": "What is the chemical element with atomic number 1?", "answer": "Hydrogen"},
        31: {"question": "Who is known as the father of modern chemistry?", "answer": "Antoine Lavoisier"},
        32: {"question": "Which game features heroes with unique abilities battling in teams?", "answer": "Dota 2"},
        33: {"question": "What is the formula to calculate speed?", "answer": "Distance divided by time"},
        34: {"question": "Which sport is known for the term 'home run'?", "answer": "Baseball"},
        35: {"question": "Who is the hero of the anime 'Dragon Ball Z'?", "answer": "Goku"},
        36: {"question": "What is the chemical name of baking soda?", "answer": "Sodium Bicarbonate"},
        37: {"question": "Who invented the telephone?", "answer": "Alexander Graham Bell"},
        38: {"question": "Which game is about catching creatures called Pokémon?", "answer": "Pokémon"},
        39: {"question": "What is the SI unit of temperature?", "answer": "Kelvin"},
        40: {"question": "Which sport uses a net, a ball, and two teams of eleven players each?", "answer": "Soccer"},
        41: {"question": "Who is the author of the anime 'Attack on Titan'?", "answer": "Hajime Isayama"},
        42: {"question": "What is the chemical formula of methane?", "answer": "CH4"},
        43: {"question": "Who formulated the laws of motion?", "answer": "Isaac Newton"},
        44: {"question": "Which game is played with a ball and wickets?", "answer": "Cricket"},
        45: {"question": "What is the unit of electric resistance?", "answer": "Ohm"},
        46: {"question": "Which sport is played in the Super Bowl?", "answer": "American Football"},
        47: {"question": "Who is the lead character in the anime 'Bleach'?", "answer": "Ichigo Kurosaki"},
        48: {"question": "What is the chemical name for vinegar?", "answer": "Acetic Acid"},
        49: {"question": "Who invented the light bulb?", "answer": "Thomas Edison"},
        50: {"question": "Which game is known for the phrase 'Winner Winner Chicken Dinner'?", "answer": "PUBG"},
        51: {"question": "What is the SI unit of energy?", "answer": "Joule"},
        52: {"question": "Which sport is associated with Wimbledon?", "answer": "Tennis"},
        53: {"question": "Who created the anime 'My Hero Academia'?", "answer": "Kohei Horikoshi"},
        54: {"question": "What is the chemical formula of sulfuric acid?", "answer": "H2SO4"},
        55: {"question": "Who discovered electricity?", "answer": "Benjamin Franklin"},
        56: {"question": "Which game involves building with blocks in a 3D world?", "answer": "Minecraft"},
        57: {"question": "What is the formula for calculating density?", "answer": "Mass divided by volume"},
        58: {"question": "Which sport is played on a diamond-shaped field?", "answer": "Baseball"},
        59: {"question": "Who is the main character of the anime 'Death Note'?", "answer": "Light Yagami"},
        60: {"question": "What is the chemical symbol for iron?", "answer": "Fe"},
        61: {"question": "Who is known as the father of modern biology?", "answer": "Charles Darwin"},
        62: {"question": "Which game is famous for the phrase 'Fortnite Victory Royale'?", "answer": "Fortnite"},
        63: {"question": "What is the SI unit of pressure?", "answer": "Pascal"},
        64: {"question": "Which sport involves hitting a shuttlecock over a net?", "answer": "Badminton"},
        65: {"question": "Who created the anime 'One Punch Man'?", "answer": "ONE"},
        66: {"question": "What is the chemical formula for glucose?", "answer": "C6H12O6"},
        67: {"question": "Who discovered the theory of evolution?", "answer": "Charles Darwin"},
        68: {"question": "Which game involves farming and village life, called 'Stardew Valley'?", "answer": "Stardew Valley"},
        69: {"question": "What is the formula to calculate acceleration?", "answer": "Change in velocity divided by time"},
        70: {"question": "Which sport is known as the 'gentleman's game'?", "answer": "Cricket"},
        71: {"question": "Who is the main protagonist of 'Sword Art Online' anime?", "answer": "Kirito"},
        72: {"question": "What is the chemical symbol for sodium?", "answer": "Na"},
        73: {"question": "Who invented the airplane?", "answer": "Wright Brothers"},
        74: {"question": "Which game is a card game with 'Hearthstone' as a popular title?", "answer": "Hearthstone"},
        75: {"question": "What is the SI unit of frequency?", "answer": "Hertz"},
        76: {"question": "Which sport involves a ball, a hoop, and dribbling?", "answer": "Basketball"},
        77: {"question": "Who is the author of the anime 'Tokyo Ghoul'?", "answer": "Sui Ishida"},
        78: {"question": "What is the chemical formula for hydrochloric acid?", "answer": "HCl"},
        79: {"question": "Who discovered the electron?", "answer": "J.J. Thomson"},
        80: {"question": "Which game involves capturing territory using colored ink?", "answer": "Splatoon"},
        81: {"question": "What is the formula for calculating work done?", "answer": "Force multiplied by distance"},
        82: {"question": "Which sport is played on grass and uses a small ball and clubs?", "answer": "Golf"},
        83: {"question": "Who is the main character of the anime 'Fairy Tail'?", "answer": "Natsu Dragneel"},
        84: {"question": "What is the chemical symbol for carbon?", "answer": "C"},
        85: {"question": "Who invented the radio?", "answer": "Guglielmo Marconi"},
        86: {"question": "Which game is about racing cars on tracks?", "answer": "Mario Kart"},
        87: {"question": "What is the SI unit of power?", "answer": "Watt"},
        88: {"question": "Which sport involves scoring goals using a stick and a small ball on a field?", "answer": "Field Hockey"},
        89: {"question": "Who is the creator of the anime 'Dragon Ball'?", "answer": "Akira Toriyama"},
        90: {"question": "What is the chemical name for sugar?", "answer": "Sucrose"},
        91: {"question": "Who invented the steam engine?", "answer": "James Watt"},
        92: {"question": "Which game is famous for zombies and blocky graphics?", "answer": "Minecraft"},
        93: {"question": "What is the formula to calculate kinetic energy?", "answer": "0.5 multiplied by mass multiplied by velocity squared"},
        94: {"question": "Which sport uses a bat and a ball and is popular in India?", "answer": "Cricket"},
        95: {"question": "Who is the hero of the anime 'Tokyo Ghoul'?", "answer": "Ken Kaneki"},
        96: {"question": "What is the chemical symbol for lead?", "answer": "Pb"},
        97: {"question": "Who discovered radioactivity?", "answer": "Henri Becquerel"},
        98: {"question": "Which game features heroes battling in a virtual arena, known as 'League of Legends'?", "answer": "League of Legends"},
        99: {"question": "What is the formula for Ohm's Law?", "answer": "Voltage equals current multiplied by resistance"},
        100: {"question": "Which sport is played on a court with rackets and a net?", "answer": "Tennis"},
        101: {"question": "Who is the main character of the anime 'My Hero Academia'?", "answer": "Izuku Midoriya"},
        102: {"question": "What is the chemical formula for ethanol?", "answer": "C2H5OH"},
        103: {"question": "Who invented the computer?", "answer": "Charles Babbage"},
        104: {"question": "Which game is known for building forts and fighting, called 'Fortnite'?", "answer": "Fortnite"},
        105: {"question": "What is the SI unit of length?", "answer": "Meter"},
        106: {"question": "Which sport involves scoring points by throwing a ball into a hoop?", "answer": "Basketball"},
        107: {"question": "Who is the main character of the anime 'One Punch Man'?", "answer": "Saitama"},
        108: {"question": "What is the chemical symbol for helium?", "answer": "He"},
        109: {"question": "Who discovered the law of universal gravitation?", "answer": "Isaac Newton"},
        110: {"question": "Which game is about surviving on an island called 'Fortnite'?", "answer": "Fortnite"},
        111: {"question": "What is the formula to calculate pressure?", "answer": "Force divided by area"},
        112: {"question": "Which sport uses a ball and a bat and is popular in the USA?", "answer": "Baseball"},
        113: {"question": "Who is the main character of the anime 'Black Clover'?", "answer": "Asta"},
        114: {"question": "What is the chemical formula for nitric acid?", "answer": "HNO3"},
        115: {"question": "Who invented the World Wide Web?", "answer": "Tim Berners-Lee"},
        116: {"question": "Which game is a puzzle-platformer about stacking blocks?", "answer": "Tetris"},
        117: {"question": "What is the SI unit of mass?", "answer": "Kilogram"},
        118: {"question": "Which sport involves hitting a small ball into holes on a course?", "answer": "Golf"},
        119: {"question": "Who is the protagonist of the anime 'Death Note'?", "answer": "Light Yagami"},
        120: {"question": "What is the chemical symbol for silver?", "answer": "Ag"},
        121: {"question": "Who invented the telescope?", "answer": "Hans Lippershey"},
        122: {"question": "Which game involves racing futuristic vehicles, called 'F-Zero'?", "answer": "F-Zero"},
        123: {"question": "What is the formula for momentum?", "answer": "Mass multiplied by velocity"},
        124: {"question": "Which sport is played on a rectangular field with goalposts?", "answer": "Rugby"},
        125: {"question": "Who is the main character in the anime 'Naruto'?", "answer": "Naruto Uzumaki"},
        126: {"question": "What is the chemical formula for baking soda?", "answer": "NaHCO3"},
        127: {"question": "Who invented the electric motor?", "answer": "Michael Faraday"},
        128: {"question": "Which game involves card battles in a fantasy world?", "answer": "Magic: The Gathering"},
        129: {"question": "What is the SI unit of temperature in everyday use?", "answer": "Celsius"},
        130: {"question": "Which sport involves two teams trying to score goals with a ball on ice?", "answer": "Ice Hockey"},
        131: {"question": "Who is the author of the anime 'Naruto'?", "answer": "Masashi Kishimoto"},
        132: {"question": "What is the chemical symbol for potassium?", "answer": "K"},
        133: {"question": "Who discovered the law of conservation of mass?", "answer": "Antoine Lavoisier"},
        134: {"question": "Which anime features a character named Luffy?", "answer": "One Piece"},
        135: {"question": "What is the chemical formula of baking powder?", "answer": "Mixture of baking soda and acid"},
        136: {"question": "Who invented the first practical telephone?", "answer": "Alexander Graham Bell"},
        137: {"question": "Which game is a famous battle royale game?", "answer": "Fortnite"},
        138: {"question": "What is the SI unit for luminous intensity?", "answer": "Candela"},
        139: {"question": "Which sport has the term 'touchdown'?", "answer": "American Football"},
        140: {"question": "Who is the protagonist of the anime 'Bleach'?", "answer": "Ichigo Kurosaki"},
        141: {"question": "What is the chemical symbol for chlorine?", "answer": "Cl"},
        142: {"question": "Who discovered X-rays?", "answer": "Wilhelm Röntgen"},
        143: {"question": "Which game involves placing Tetris blocks to clear lines?", "answer": "Tetris"},
        144: {"question": "What is the formula for calculating potential energy?", "answer": "Mass times gravity times height"},
        145: {"question": "Which sport uses a small ball and a curved stick?", "answer": "Field Hockey"},
        146: {"question": "Who is the main character of the anime 'Dragon Ball'?", "answer": "Goku"},
        147: {"question": "What is the chemical formula for carbon monoxide?", "answer": "CO"},
        148: {"question": "Who invented the first successful airplane?", "answer": "Wright Brothers"},
        149: {"question": "Which game is about defending a base against waves of enemies?", "answer": "Tower Defense"},
        150: {"question": "What is the SI unit of electric charge?", "answer": "Coulomb"},
        151: {"question": "Which sport involves ice skating and scoring goals?", "answer": "Ice Hockey"},
        152: {"question": "Who is the lead character in the anime 'One Piece'?", "answer": "Monkey D. Luffy"},
        153: {"question": "What is the chemical name for rust?", "answer": "Iron Oxide"},
        154: {"question": "Who invented the electric light bulb?", "answer": "Thomas Edison"},
        155: {"question": "Which game is famous for the 'Battle Bus'?", "answer": "Fortnite"},
        156: {"question": "What is the formula to calculate work done?", "answer": "Force times distance"},
        157: {"question": "Which sport is played with a racket and shuttlecock?", "answer": "Badminton"},
        158: {"question": "Who is the protagonist of the anime 'My Hero Academia'?", "answer": "Izuku Midoriya"},
        159: {"question": "What is the chemical symbol for neon?", "answer": "Ne"},
        160: {"question": "Who discovered the law of electromagnetic induction?", "answer": "Michael Faraday"},
        161: {"question": "Which game is about catching creatures called Pokémon?", "answer": "Pokémon"},
        162: {"question": "What is the SI unit of luminous flux?", "answer": "Lumen"},
        163: {"question": "Which sport involves scoring points by running between wickets?", "answer": "Cricket"},
        164: {"question": "Who is the creator of the anime 'Attack on Titan'?", "answer": "Hajime Isayama"},
        165: {"question": "What is the chemical formula for nitric oxide?", "answer": "NO"},
        166: {"question": "Who invented the periodic table?", "answer": "Dmitri Mendeleev"},
        167: {"question": "Which game involves building and crafting in a blocky world?", "answer": "Minecraft"},
        168: {"question": "What is the formula for calculating frequency?", "answer": "1 divided by period"},
        169: {"question": "Which sport uses terms like 'set' and 'serve'?", "answer": "Tennis"},
        170: {"question": "Who is the main character of the anime 'Black Clover'?", "answer": "Asta"},
        171: {"question": "What is the chemical symbol for copper?", "answer": "Cu"},
        172: {"question": "Who discovered the structure of DNA?", "answer": "Watson and Crick"},
        173: {"question": "Which game is known for its blocky zombies?", "answer": "Minecraft"},
        174: {"question": "What is the SI unit of capacitance?", "answer": "Farad"},
        175: {"question": "Which sport involves hitting a small ball into holes?", "answer": "Golf"},
        176: {"question": "Who is the hero of the anime 'Sword Art Online'?", "answer": "Kirito"},
        177: {"question": "What is the chemical formula for ozone?", "answer": "O3"},
        178: {"question": "Who invented the first vaccine?", "answer": "Edward Jenner"},
        179: {"question": "Which game is famous for its virtual building and shooting mechanics?", "answer": "Fortnite"},
        180: {"question": "What is the formula for calculating voltage?", "answer": "Current times resistance"},
        181: {"question": "Which sport is played on a grass field with a ball and a bat?", "answer": "Cricket"},
        182: {"question": "Who is the main character of the anime 'Death Note'?", "answer": "Light Yagami"},
        183: {"question": "What is the chemical symbol for zinc?", "answer": "Zn"},
        184: {"question": "Who discovered the neutron?", "answer": "James Chadwick"},
        185: {"question": "Which game involves strategic card battles in a fantasy setting?", "answer": "Hearthstone"},
        186: {"question": "What is the SI unit of inductance?", "answer": "Henry"},
        187: {"question": "Which sport involves a ball, goalposts, and end zones?", "answer": "American Football"},
        188: {"question": "Who is the author of the anime 'Fairy Tail'?", "answer": "Hiro Mashima"},
        189: {"question": "What is the chemical formula of acetylene?", "answer": "C2H2"},
        190: {"question": "Who invented the first practical automobile?", "answer": "Karl Benz"},
        191: {"question": "Which game involves a battle royale format with shrinking play zones?", "answer": "PUBG"},
        192: {"question": "What is the formula to calculate frequency in hertz?", "answer": "Number of cycles per second"},
        193: {"question": "Which sport uses a net and a ball but is played on sand?", "answer": "Beach Volleyball"},
        194: {"question": "Who is the main character of the anime 'Tokyo Ghoul'?", "answer": "Ken Kaneki"},
        195: {"question": "What is the chemical symbol for magnesium?", "answer": "Mg"},
        196: {"question": "Who discovered the electron?", "answer": "J.J. Thomson"},
        197: {"question": "Which game involves strategic play with colored ink?", "answer": "Splatoon"},
        198: {"question": "What is the SI unit for magnetic flux?", "answer": "Weber"},
        199: {"question": "Which sport is known as 'the fastest game on ice'?", "answer": "Ice Hockey"},
        200: {"question": "Who created the anime 'One Punch Man'?", "answer": "ONE"},
    }
